[package]
name = "creamui-macros"
description = "JSX syntax for CreamUI's Rust widget builders"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }

[dev-dependencies]
creamui-core = { workspace = true }
creamui-dynamic = { workspace = true }
creamui-image = { path = "../image" }
creamui-jsx = { workspace = true }
creamui-reactive = { workspace = true }
creamui-theme = { workspace = true }
creamui-widgets = { workspace = true }
